#全局数据库信息配置文件
#Author: cui_jian

#全局统一数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.21.1.147:3306/shop_jsdjy?useUnicode=true&characterEncoding=utf8&serverTimezone=CST&useSSL=false
    username: root
    password: Centit@001
    max-active: 10
    max-idle: 10
    max-wait: 60000
    min-idle: 5
    initial-size: 5
  redis:
    host: 172.21.1.145
    port: 6379
    lettuce:
      pool:
        max-idle: 5000
        max-active: 5000
    timeout: 5000