#移动支付服务配置文件
#Author: cui_jian

spring:
  application:
    name: pay
  #  datasource:
  #    driver-class-name: oracle.jdbc.OracleDriver
  #    url: jdbc:oracle:thin:@192.168.131.102:1521:mipdb
  #    username: JSSJTT
  #    password: JSSJTT
  #    max-idle: 10
  #    max-wait: 10000
  #    min-idle: 5
  #    initial-size: 5

  #Redis配置
  redis:
    host: 193.168.1.233
    #Redis服务器连接密码（默认为空）
    password:
    #Redis数据库索引（默认为0）
    database: 5
    port: 6379
    #连接超时时间（毫秒）
    timeout: 300
    #这里使用的是lettuce，如果使用Jedis，把下面的lettuce改成Jedis即可
    lettuce:
      pool:
        #连接池中的最大空闲连接
        max-idle: 8
        #连接池中的最小空闲连接
        min-idle: 0
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1




#mybatis配置
mybatis:
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mappers/*.xml #指定resources下面的mappers文件夹
  #  typeAliasesPackage: com.centit.organizeuser.organizeuserserver.webmgr.po

  #spring boot集成mybatis的方式打印sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#日志方式sql打印
#logging:
#  level:
#    com.example.demo.dao: debug

pay:
  alipay:
    appId: 2021002155658242
    appPrivateKey: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCkwREjcR3TEdP0IRKoVmC4ySRW1VAxK5IxSctUHwNsJ20IjmLULl042aNrDuXbaK4PHq87VR9HTnteb+fWG0smRQB5t7tV4j6J5FqLWiwhYch9uaarm7/6NQ1OTfAHp89nl6d6zqqsD93mgIfJVIeAP+0TMGqqhqwN7AnxDVjYiPr69R97a7/c4KTW1LCbrcQCx6MoXW8X1sbRNEybLgi3q/xCcb9cifpNC6P5F8kKFYnKzQnsGnJ+3lTwbfxOmNnUmHlhAJGDkpitsbz8H/83TezOJBWZ9SUd069qxQ9QCnKu2S6VMntC3GrzLb2/woyJ96tkiKwNhfeFF9Rw7jhzAgMBAAECggEBAKSkG1Bjtf47jqgkdNSsnTOMLjhoKx83/3wp1ntWEsF+FMO8Jp8LRjWNqHVQCfvc/DQ34b1VL1C+6SJSike4Nr0jr3nzVc5ZrU13WdRwZDFn2kdpw1ky6AJOCeH6mKfN1sIbF07uQDh6ErJKN2fGhTJwr6XBeJa4xi+TdcviHqsjfFhD/xa3cr/t9WE08UyGu07qXkD18uQ+rJXdgmOaeXR9OlR0BgiFLdxfRvJ6uojL+q9oN23BEjMhdMR+eAZ1j9rv9QB0zGI1l3a3iXs7HsPpclJfukaaDXa2SDblqpKWFlAn1OzNY85tQfUn1IAd1FiGf++8i39B1gf6q9p6ncECgYEA355CgSjnW4LgrFJmFUQObIsOF3B0Da7o2HueuFFwEAXoAXDqOpq0Qdg/0Fz8Kid46FbuucxiCY+Y8W0y7hdHERdKDX1NgPFUmnr0SMPzk4ee50A2aR4o7KYmmhgce5PhXSALyZXBk4ycOj4SKI8qQ9ji1iBFC480N4jCDfxy9PkCgYEAvJypRVyDkr6YjW7ck7zYtX48/SQTxNfTbPLOgdF0bv8imELopvcrrNk/9D/2G2x90KyZKWcYLXDYANBREXrz0kZyLhiqXjyVS4e5D0QN3HAH3pdpQRMB4Z/8RAGAv2tqi+jmvEXOrzi5jS6WrLCv+EzoxTtFmZlVD0Qlak9+b8sCgYEAhnsRucVUpccmwNtpAv8Dwak610PMt3HqHE7z3Bs1zp0OstcqNgZVw4d+kRtqlxtX7jphpSFSEDfoncCzMVaUaaXc5hHmK1Z3L9Qj1yLo+F9GZAJM9pipufAOJPu9HWCI1s1v6VKDsO2OAsTTfMrkexsTB/0uKM59c6xuL6UTqVkCgYAW2dQYNzEpojXRTNEkhQisVHMHKEvM2WkgFfq2961nlTmXwON29xMvidKZwPYMNIS5t2+G+JqRRs6kqphnycGohChpNUvOxwA/el4NX21ee6Q4b5es7qSXtU5W3ue+SUFLWhg6TyrPR8wTMsXGflGTf53j515zUYRgqRzvWFo1KQKBgQCgZz5hPuouJ499nHN8bps3PptMFSiuJV/7j7VwijUoZTAcOBeisnthP204XAdcoCb+8UG+OQKvpFEzZAipdwxwMzH7gMqhGZfcOWMOOYy/ZAvfg2gzr8J+RQEBR0PY+E/yQEh/uy3k6hWc1INWByuHinrIkZF6dIW0tWo51GCmMA==
    appPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApMERI3Ed0xHT9CESqFZguMkkVtVQMSuSMUnLVB8DbCdtCI5i1C5dONmjaw7l22iuDx6vO1UfR057Xm/n1htLJkUAebe7VeI+ieRai1osIWHIfbmmq5u/+jUNTk3wB6fPZ5enes6qrA/d5oCHyVSHgD/tEzBqqoasDewJ8Q1Y2Ij6+vUfe2u/3OCk1tSwm63EAsejKF1vF9bG0TRMmy4It6v8QnG/XIn6TQuj+RfJChWJys0J7Bpyft5U8G38TpjZ1Jh5YQCRg5KYrbG8/B//N03sziQVmfUlHdOvasUPUApyrtkulTJ7Qtxq8y29v8KMiferZIisDYX3hRfUcO44cwIDAQAB
    publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjguF74b+Cw33bZsoPdrccp7cCxLF3cwWXGEwuGq+semtp7c/TnbR9d3cN0MCUuwpoZaZbxFUpre8gPrX+q7zbmyjVTV9Of4dBYDTnZ5puIMW6wVgvaMQishkUJkjYZKgAIDHIYUjVnBpCfIYx3BpnAeXnh4bhXQJUFuQCi67ZMpIAuKAaDhUHpvTTgUgnlNay88lHl+Gt9AUyKLcYykvVgAvn7DDf73cTL0Vrutizi/1HsmO+sUE5FLGERcBjkA7mHkxwpOg8hmZQ6n/Yps/6JQnImCKLRTJX5BsrmvAzfyD35uWv+EKeOXhk2a6NL1pQXXpsuz7YOA0sYnNebgfIwIDAQAB
    notifyUrl: https://app.jsartcentre.org/pay/notify/aliNotify
  wxpay:
    notifyUrl: https://app.jsartcentre.org/pay/notify/wxNotify
    notifyUrl_park: https://app.jsartcentre.org/pay/notify/wxNotify_park
  istest: false
