#zuul路由网关服务配置文件
#Author: cui_jian

spring:
  application:
    name: gateway
#  datasource:
#    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@192.168.131.102:1521:mipdb
#    username: JSSJTT
#    password: JSSJTT
#    max-idle: 10
#    max-wait: 10000
#    min-idle: 5
#    initial-size: 5


#mybatis配置
mybatis:
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mappers/*.xml #指定resources下面的mappers文件夹
  #  typeAliasesPackage: com.centit.organizeuser.organizeuserserver.webmgr.po

  #spring boot集成mybatis的方式打印sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#日志方式sql打印
#logging:
#  level:
#    com.example.demo.dao: debug


#zuul路由网关服务
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: provider
    api-b:
      path: /api-b/**
      serviceId: consumer
    framework/system:
      path: /framework/system/**
      serviceId: framework
    file:
      path: /file/**
      serviceId: file
    shop:
      path: /pay/**
      serviceId: pay
    shopping:
      path: /shopping/**
      serviceId: shopping
    admin:
      path: /admin/**
      serviceId: admin
    ticket:
      path: /ticket/**
      serviceId: ticket